### ISSUE TITLE
Feature: Allow sequences or arrays for generated types

### ISSUE THREAD

**Issue by prosconi** [fsprojects/FSharp.Data.Xsd#12]
### Description
Currently, the constructors for generated types on repeating elements is an array. It would be nice if it can be sequences so the data can be streamed without possibly loading huge data structures in memory.

**Comment by giacomociti** [comment]
I'm afraid this is out of scope since this project directly refers source code of F# Data, including the machinery for generating types. Surely streaming data is necessary when processing huge files, but in these cases I'm fine with using `XmlReader` or `XmlWriter` at the top level while still using the provided types for inner elements

**Comment by prosconi** [comment]
Thanks for the tip. I actually do that for reading large files but didn't think about that for writing
