### ISSUE TITLE
GetSample should not return schema content

### ISSUE THREAD

**Issue by bleis-tift** [fsprojects/FSharp.Data.Xsd#13]
### Description
Provided type has the `GetSample` method.
This method returns the content that is passed as static parameter.
If I use `Schema` parameter then `GetSample` method returns the schema content.
But schema is not sample.
I think `GetSample` method should not return schema content.

### Repro steps

```fsharp
open FSharp.Data
type T = XmlProvider<Schema = @"path\to\xsd\file">

let f () =
  T.GetSample()  // this returns the content of the schema.
```

**Comment by giacomociti** [comment]
I agree `GetSample` makes no sense when using the `Schema` parameter.
Anyway I'm not so keen on fixing it because I'd like to avoid changing the original F# Data code as much as possible. This is the very same reason why I left out the (albeit useful) enhancements  provided by @jannickj for supporting scalar types https://github.com/giacomociti/FSharp.Data.Xsd/pull/8 This kind of improvements would be better addressed in the context of F# data in case this project gets merged into it. Unfortunately I still got no feedback on the existing PR  https://github.com/fsharp/FSharp.Data/pull/1004

**Comment by bleis-tift** [comment]
I see. thanks.
(Do you think this issue status should be closed?)

**Comment by giacomociti** [comment]
we can leave it open for now, as a reminder of an issue which I think is not severe, but is actual indeed. Thanks for pointing it out.

**Comment by bleis-tift** [comment]
OK. I'll leave it open.

**Comment by ovatsus** [comment]
We shouldn't emit the GetSample method when Schema is used (We do that for the CSV provider)

**Comment by giacomociti** [comment]
I'll have a look but I may need some help on this

**Comment by ovatsus** [comment]
Just passing empty on the sampleOrSampleUri param will do that

**Comment by giacomociti** [comment]
Ok, I'm closing this issue although it won't be fixed here (but it is fixed in F# Data).
