### ISSUE TITLE
Support XML schema list

### ISSUE THREAD

**Issue by Astrinus** [fsprojects/FSharp.Data.Xsd#15]
### Description

Currently a `xs:list` parses to its base type

### Repro steps

1. Unzip  [FSharp.Data.Xsd_issue.zip](https://github.com/fsprojects/FSharp.Data.Xsd/files/1155195/FSharp.Data.Xsd_issue.zip)

2. See the error in the .fsx on `od` and `Some id`

### Expected behavior

The constructor accepts `float list` for `od` and `Some float list` for `id`.

### Actual behavior

The constructor accepts `float` for `od` and `Some float` for `id`.

### Known workarounds

No idea.

### Related information 

* Operating system: Windows 10 Home; Version 1607; Build 14393.1480
* Branch: NuGet package v1.0.0
* .NET Runtime, CoreCLR or Mono Version: .NET framework 4.5.2, F# runtime 4.0

**Comment by giacomociti** [comment]
Interesting catch. I'll have a closer look in a few days. I hope we can improve on the current behavior but I'm afraid the optimal behavior is not easy to achieve.

**Comment by giacomociti** [comment]
In the meantime a workaround may be to ignore the provided properties corresponding to list types and for those elements directly use the XElement property.

**Comment by Astrinus** [comment]
I have fallen back on manual use of XAttribute / XElement / XDocument for the time being; now works so it is not urgent.

**Comment by giacomociti** [comment]
commit cf7d0e2e8d987a8765bb15620668ba5a78020ce3 should mitigate the issue. For simple types of the list or union variety we simply fallback to `string `properties. This adds very little to the aforementioned workaround of directly using the underlying `XElement`, but at least we avoid the misleading behavior of providing for example a property of type `float` instead of `float list`.
Doing the right thing and providing a `float list` is not impossible but I think it is out of scope for this project, which is just a thin wrapper around the XML type provider of F# Data.
